sudo: required

language: generic

services:
- docker

arch:
  packages:
  - openmpi
  - cpplint
  script:
  - make test

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
