
tobin: tobin.cpp
	g++ -o tobin tobin.cpp

totxt: totxt.cpp
	g++ -o totxt totxt.cpp

main: main.cpp
	mpicxx -std=c++98 -O3 -o main main.cpp 

clean : 
	rm -f *.dat *.txt  *.svg print generate main random compare *.map totxt a.out *.bin tobin